# Generated by Django 4.2.13 on 2024-05-07 22:35

from django.db import migrations, models
import django.db.models.deletion
import incapacidades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Escribe el codigo de la AFP...', max_length=32, unique=True, verbose_name='Codigo AFP')),
                ('nit', models.CharField(help_text='Escribe el NIT de la AFP..', max_length=32, verbose_name='NIT')),
                ('nombre', models.CharField(help_text='Escribe el nombre de la AFP...', max_length=64, verbose_name='Nombre de la entidad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Escribe el codigo de centro de costos...', max_length=16, null=True, verbose_name='Codigo del centro de costos')),
                ('nombre', models.CharField(help_text='Escribe el nombre del centro de costos...', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costos',
                'db_table': 'ccostos',
            },
        ),
        migrations.CreateModel(
            name='ClaseIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe la incapacidad', max_length=64, verbose_name='Nombre de la incapacidad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clase de Incapacidad',
                'verbose_name_plural': 'Clases de Incapacidades',
                'db_table': 'clases_incapacidades',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Escribe el codigo del concepto...', max_length=3, verbose_name='Codigo del concepto')),
                ('nombre', models.CharField(help_text='Escribe el nombre del concepto...', max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conceptos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Escribe el codigo del diagnostico...', max_length=16, verbose_name='Codigo del diagnostico')),
                ('nombre', models.CharField(help_text='Escribe el nombre del diagnostico...', max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docto_empleado', models.CharField(help_text='Escribe el numero de documento...', max_length=64, unique=True, verbose_name='Numero de documento')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombres completos')),
                ('genero', incapacidades.models.GenderField(choices=[(1, 'Femenino'), (0, 'Masculino')], db_comment='Campo para el genero de la persona. 1: Femenino, 0: Masculino', help_text='1: Femenino, 0: Masculino')),
                ('fecha_nacimiento', models.DateField(help_text='Escribe o selecciona la fecha de nacimiento...', verbose_name='Fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(help_text='Escribe o selecciona la fecha de ingreso...', verbose_name='Fecha de ingreso')),
                ('estado', incapacidades.models.StatusField(choices=[(0, 'Activo'), (1, 'Retirado')])),
                ('arl_nit', models.CharField(help_text='Escribe el NIT de la ARL...', max_length=32, verbose_name='NIT de la ARL')),
                ('arl_nombre', models.CharField(help_text='Escribe el nombre de la ARL...', max_length=64, verbose_name='Nombre de la ARL')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('afp', models.ForeignKey(db_column='afp_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.afp')),
                ('centro_costos', models.ManyToManyField(related_name='ccostos_asignados', to='incapacidades.centrocosto')),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Escribe el codigo de la EPS...', max_length=32, verbose_name='Codigo de la EPS')),
                ('nit', models.CharField(help_text='Escribe el NIT de la EPS...', max_length=32, unique=True)),
                ('nombre', models.CharField(help_text='Escribe el nombre de la EPS...', max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPSs',
            },
        ),
        migrations.CreateModel(
            name='EstadoIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe el estado de la incapacidad...', max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado de Incapacidad',
                'verbose_name_plural': 'Estados de Incapacidades',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_incapacidad', models.CharField(help_text='Escribe el codigo de la incapacidad', max_length=32, unique=True, verbose_name='Codigo de la incapacidad')),
                ('serie', models.CharField(help_text='Escribe el numero de serie', max_length=32, unique=True)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prorroga', models.SmallIntegerField()),
                ('dias', models.SmallIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calendario', models.CharField(blank=True, max_length=32, null=True)),
                ('valor_cia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado_entidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pendiente_entidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('llevada_gasto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mayor_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpto_472', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('genera_pago', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('afp', models.ForeignKey(db_column='afp_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.afp')),
                ('centro_costo', models.ForeignKey(db_column='ccosto_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.centrocosto')),
                ('concepto', models.ForeignKey(db_column='concepto_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.concepto')),
                ('diagnostico', models.ForeignKey(db_column='diagnostico_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.diagnostico')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.empleado')),
                ('eps', models.ForeignKey(db_column='eps_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.eps')),
                ('estado_incapacidad', models.ForeignKey(db_column='estado_inc_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='incapacidades.estadoincapacidad', verbose_name='Estado de incapacidad')),
                ('incapacidad', models.ForeignKey(db_column='clase_inc_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='FechaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(help_text='Escribe o selecciona la fecha inicial...', verbose_name='Fecha inicial real')),
                ('fecha_final', models.DateField(help_text='Escribe o selecciona la fecha final...', verbose_name='Fecha final real')),
                ('cuenta_cobrar', models.DecimalField(decimal_places=2, help_text='Escribe el valor de la cuenta x cobrar...', max_digits=10, verbose_name='Cuenta x cobrar')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incapacidades.movimiento')),
            ],
            options={
                'verbose_name': 'Fechas de Distribucion',
                'verbose_name_plural': 'Fechas de Distribucion',
                'db_table': 'fechas_distribucion',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='eps',
            field=models.ForeignKey(db_column='eps_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.eps'),
        ),
    ]
