# Generated by Django 4.2.11 on 2024-05-02 18:25

from django.db import migrations, models
import django.db.models.deletion
import incapacidades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docto_empleado', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('genero', incapacidades.models.GenderField(choices=[(1, 'Femenino'), (0, 'Masculino')], db_comment='Campo para el genero de la persona. 1: Femenino, 0: Masculino', help_text='1: Femenino, 0: Masculino')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('estado', incapacidades.models.StatusField(choices=[(0, 'Activo'), (1, 'Retirado')])),
                ('arl_nit', models.CharField(max_length=32)),
                ('arl_nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('afp', models.ForeignKey(db_column='afp_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.afp')),
                ('centro_costos', models.ManyToManyField(related_name='ccostos_asignados', to='incapacidades.centrocosto')),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_incapacidad', models.CharField(max_length=32, unique=True)),
                ('serie', models.CharField(max_length=32, unique=True)),
                ('fecha_recepcion', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('prorroga', models.SmallIntegerField()),
                ('dias', models.SmallIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calendario', models.CharField(max_length=32)),
                ('valor_cia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuenta_cobrar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagado_entidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('llevada_gasto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mayor_valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cpto_472', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_estado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('genera_pago', models.IntegerField()),
                ('afp', models.ForeignKey(db_column='afp_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.afp')),
                ('centro_costo', models.ForeignKey(db_column='ccosto_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.centrocosto')),
                ('concepto', models.ForeignKey(db_column='concepto_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.concepto')),
                ('diagnostico', models.ForeignKey(db_column='diagnostico_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.diagnostico')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.empleado')),
                ('eps', models.ForeignKey(db_column='eps_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.eps')),
            ],
        ),
        migrations.CreateModel(
            name='FechaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial_real', models.DateTimeField()),
                ('fecha_final_real', models.DateTimeField()),
                ('cuenta_cobrar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incapacidades.movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='eps',
            field=models.ForeignKey(db_column='eps_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.eps'),
        ),
    ]
