# Generated by Django 4.2.11 on 2024-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afp',
            options={'verbose_name': 'AFP', 'verbose_name_plural': 'AFPs'},
        ),
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'verbose_name': 'Centro de Costo', 'verbose_name_plural': 'Centros de Costos'},
        ),
        migrations.AlterModelOptions(
            name='claseincapacidad',
            options={'verbose_name': 'Clase de Incapacidad', 'verbose_name_plural': 'Clases de Incapacidades'},
        ),
        migrations.AlterModelOptions(
            name='eps',
            options={'verbose_name': 'EPS', 'verbose_name_plural': 'EPSs'},
        ),
        migrations.AlterModelOptions(
            name='estadoincapacidad',
            options={'verbose_name': 'Estado de Incapacidad', 'verbose_name_plural': 'Estados de Incapacidades'},
        ),
        migrations.AlterModelOptions(
            name='fechadistribucion',
            options={'verbose_name': 'Fechas de Distribucion', 'verbose_name_plural': 'Fechas de Distribucion'},
        ),
        migrations.AlterField(
            model_name='afp',
            name='nit',
            field=models.CharField(max_length=32, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='afp',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre de la entidad'),
        ),
        migrations.AlterModelTable(
            name='centrocosto',
            table='ccostos',
        ),
        migrations.AlterModelTable(
            name='claseincapacidad',
            table='clases_incapacidades',
        ),
        migrations.AlterModelTable(
            name='concepto',
            table='conceptos',
        ),
        migrations.AlterModelTable(
            name='fechadistribucion',
            table='fechas_distribucion',
        ),
        migrations.AlterModelTable(
            name='movimiento',
            table='movimientos',
        ),
    ]
