# Generated by Django 4.2.11 on 2024-05-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la EPS...', max_length=32, unique=True, verbose_name='Codigo de la EPS'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='nit',
            field=models.CharField(help_text='Escribe el NIT de la EPS...', max_length=32),
        ),
    ]
