# Generated by Django 4.2.11 on 2024-05-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0002_alter_afp_options_alter_centrocosto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afp',
            name='codigo',
            field=models.CharField(max_length=32, null=True, verbose_name='Codigo AFP'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='codigo',
            field=models.CharField(max_length=3, null=True, verbose_name='Codigo del concepto'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(max_length=16, null=True, verbose_name='Codigo del diagnostico'),
        ),
        migrations.AddField(
            model_name='eps',
            name='codigo',
            field=models.CharField(max_length=32, null=True, verbose_name='Codigo de la EPS'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl_nit',
            field=models.CharField(max_length=32, verbose_name='NIT de la ARL'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl_nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre de la ARL'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombres completos'),
        ),
    ]
