# Generated by Django 4.2.11 on 2024-05-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0003_afp_codigo_concepto_codigo_diagnostico_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='incapacidad',
            field=models.ForeignKey(db_column='incapacidad_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad'),
        ),
    ]
