# Generated by Django 4.2.11 on 2024-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0004_alter_movimiento_genera_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='prorroga',
            field=models.BooleanField(default=False),
        ),
    ]
