# Generated by Django 4.2.11 on 2024-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0004_movimiento_incapacidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechadistribucion',
            name='fecha_final_real',
        ),
        migrations.RemoveField(
            model_name='fechadistribucion',
            name='fecha_inicial_real',
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='fecha_final',
            field=models.DateField(help_text='Escribe o selecciona la fecha final...', null=True, verbose_name='Fecha final real'),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='fecha_inicial',
            field=models.DateField(help_text='Escribe o selecciona la fecha inicial...', null=True, verbose_name='Fecha inicial real'),
        ),
        migrations.AlterField(
            model_name='afp',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la AFP', max_length=32, null=True, verbose_name='Codigo AFP'),
        ),
        migrations.AlterField(
            model_name='afp',
            name='nit',
            field=models.CharField(help_text='Escribe el NIT de la AFP..', max_length=32, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='afp',
            name='nombre',
            field=models.CharField(help_text='Escribe el nombre de la AFP...', max_length=64, verbose_name='Nombre de la entidad'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='nombre',
            field=models.CharField(help_text='Escribe el nombre del centro de costos...', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='claseincapacidad',
            name='nombre',
            field=models.CharField(help_text='Escribe la incapacidad', max_length=64, verbose_name='Nombre de la incapacidad'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo del concepto...', max_length=3, null=True, verbose_name='Codigo del concepto'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='nombre',
            field=models.CharField(help_text='Escribe el nombre del concepto...', max_length=64),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo del diagnostico...', max_length=16, null=True, verbose_name='Codigo del diagnostico'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='nombre',
            field=models.CharField(help_text='Escribe el nombre del diagnostico...', max_length=64),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl_nit',
            field=models.CharField(help_text='Escribe el NIT de la ARL...', max_length=32, verbose_name='NIT de la ARL'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl_nombre',
            field=models.CharField(help_text='Escribe el nombre de la ARL...', max_length=64, verbose_name='Nombre de la ARL'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='docto_empleado',
            field=models.CharField(help_text='Escribe el numero de documento...', max_length=64, unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(help_text='Escribe o selecciona la fecha de ingreso...', verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Escribe o selecciona la fecha de nacimiento...', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la EPS...', max_length=32, null=True, verbose_name='Codigo de la EPS'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='nit',
            field=models.CharField(help_text='Escribe el NIT de la EPS...', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='eps',
            name='nombre',
            field=models.CharField(help_text='Escribe el nombre de la EPS...', max_length=64),
        ),
        migrations.AlterField(
            model_name='estadoincapacidad',
            name='nombre',
            field=models.CharField(help_text='Escribe el estado de la incapacidad...', max_length=64),
        ),
        migrations.AlterField(
            model_name='fechadistribucion',
            name='cuenta_cobrar',
            field=models.DecimalField(decimal_places=2, help_text='Escribe el valor de la cuenta x cobrar...', max_digits=8, verbose_name='Cuenta x cobrar'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cod_incapacidad',
            field=models.CharField(help_text='Escribe el codigo de la incapacidad', max_length=32, unique=True, verbose_name='Codigo de la incapacidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='serie',
            field=models.CharField(help_text='Escribe el numero de serie', max_length=32, unique=True),
        ),
    ]
