# Generated by Django 4.2.11 on 2024-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0005_remove_fechadistribucion_fecha_final_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afp',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la AFP...', max_length=32, null=True, verbose_name='Codigo AFP'),
        ),
    ]
