# Generated by Django 4.2.11 on 2024-05-14 23:02

from django.db import migrations
import incapacidades.models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0005_alter_movimiento_prorroga'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='responsable',
            field=incapacidades.models.EntityField(choices=[(0, 'Arl'), (1, 'Empresa'), (2, 'Eps')], db_comment='Campo para almacenar el responsable del pago de la incapacidad, si el responsable es la empresa cubrira los dos primeros dias, para el resto de los casos lo cubre la entidad.', default=1, help_text='0: ARL, 1: Empresa y 2: EPS'),
        ),
    ]
