# Generated by Django 4.2.11 on 2024-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0006_concepto_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseincapacidad',
            name='dias_empresa',
            field=models.SmallIntegerField(default=0, help_text='Escribe el numero de dias que va a pagar la empresa', verbose_name='# dias asume empresa'),
        ),
    ]
