# Generated by Django 4.2.11 on 2024-05-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0007_alter_afp_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo del concepto...', max_length=3, verbose_name='Codigo del concepto'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo del diagnostico...', max_length=16, verbose_name='Codigo del diagnostico'),
        ),
        migrations.AlterField(
            model_name='eps',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la EPS...', max_length=32, verbose_name='Codigo de la EPS'),
        ),
        migrations.AlterField(
            model_name='fechadistribucion',
            name='fecha_final',
            field=models.DateField(help_text='Escribe o selecciona la fecha final...', verbose_name='Fecha final real'),
        ),
        migrations.AlterField(
            model_name='fechadistribucion',
            name='fecha_inicial',
            field=models.DateField(help_text='Escribe o selecciona la fecha inicial...', verbose_name='Fecha inicial real'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='incapacidad',
            field=models.ForeignKey(db_column='incapacidad_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad'),
        ),
    ]
