# Generated by Django 4.2.11 on 2024-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0009_centrocosto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_estado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
