# Generated by Django 4.2.11 on 2024-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0009_alter_movimiento_llevada_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='mayor_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
