# Generated by Django 4.2.11 on 2024-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0010_alter_movimiento_fecha_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='calendario',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_estado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
