# Generated by Django 4.2.11 on 2024-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0011_alter_movimiento_calendario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
