# Generated by Django 4.2.11 on 2024-05-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0011_alter_movimiento_cpto_472'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='centro_costos',
        ),
    ]
