# Generated by Django 4.2.11 on 2024-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0012_movimiento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='calendario',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_estado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
