# Generated by Django 4.2.11 on 2024-05-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0012_remove_empleado_centro_costos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='salario',
        ),
    ]
