# Generated by Django 4.2.11 on 2024-05-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0013_remove_movimiento_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechadistribucion',
            name='empresa_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='empresa_valor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='entidad_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='entidad_valor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fechadistribucion',
            name='total_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
