# Generated by Django 4.2.11 on 2024-05-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0014_alter_movimiento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado_incapacidad',
            field=models.ForeignKey(db_column='estado_inc_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='incapacidades.estadoincapacidad', verbose_name='Estado de incapacidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='incapacidad',
            field=models.ForeignKey(db_column='claser_inc_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad'),
        ),
    ]
