# Generated by Django 4.2.11 on 2024-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0014_fechadistribucion_empresa_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadistribucion',
            name='empresa_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fechadistribucion',
            name='entidad_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
