# Generated by Django 4.2.11 on 2024-05-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0015_movimiento_estado_incapacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='incapacidad',
            field=models.ForeignKey(db_column='clase_inc_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad'),
        ),
    ]
