# Generated by Django 4.2.11 on 2024-05-03 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0016_alter_movimiento_incapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='incapacidad',
            field=models.ForeignKey(db_column='clase_inc_id', on_delete=django.db.models.deletion.PROTECT, to='incapacidades.claseincapacidad'),
        ),
    ]
