# Generated by Django 4.2.11 on 2024-05-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0016_remove_fechadistribucion_cuenta_cobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadistribucion',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_distribucion', to='incapacidades.movimiento'),
        ),
    ]
