# Generated by Django 4.2.11 on 2024-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0017_alter_movimiento_incapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='pendiente_entidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
