# Generated by Django 4.2.11 on 2024-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0017_alter_fechadistribucion_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='calendario',
        ),
    ]
