# Generated by Django 4.2.11 on 2024-05-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0018_movimiento_pendiente_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadistribucion',
            name='cuenta_cobrar',
            field=models.DecimalField(decimal_places=2, help_text='Escribe el valor de la cuenta x cobrar...', max_digits=10, verbose_name='Cuenta x cobrar'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cpto_472',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta_cobrar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='llevada_gasto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='mayor_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='pagado_entidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='pendiente_entidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='valor_cia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
