# Generated by Django 4.2.11 on 2024-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0018_remove_movimiento_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechadistribucion',
            name='calendario',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
