# Generated by Django 4.2.13 on 2024-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0019_alter_fechadistribucion_cuenta_cobrar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afp',
            name='codigo',
            field=models.CharField(help_text='Escribe el codigo de la AFP...', max_length=32, unique=True, verbose_name='Codigo AFP'),
        ),
        migrations.AlterField(
            model_name='afp',
            name='nit',
            field=models.CharField(help_text='Escribe el NIT de la AFP..', max_length=32, verbose_name='NIT'),
        ),
    ]
