# Generated by Django 4.2.11 on 2024-05-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0020_afp_actualizado_centrocosto_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoincapacidad',
            name='codigo',
            field=models.CharField(blank=True, help_text='Escribe el codigo del estado de incapacidad...', max_length=3, null=True, verbose_name='Codigo del estado de incapacidad'),
        ),
    ]
