# Generated by Django 4.2.11 on 2024-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0021_estadoincapacidad_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoincapacidad',
            name='codigo',
            field=models.CharField(blank=True, help_text='Escribe el codigo del estado de incapacidad...', max_length=3, null=True, verbose_name='Codigo estado de incapacidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cod_incapacidad',
            field=models.CharField(blank=True, help_text='Escribe el codigo de la incapacidad', max_length=32, null=True, verbose_name='Codigo de la incapacidad'),
        ),
    ]
