# Generated by Django 4.2.11 on 2024-05-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidades', '0022_alter_estadoincapacidad_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='dias',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_recepcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
